// <auto-generated />
using System;
using BookingSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cod"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<int>("CodUsuarioPrestador")
                        .HasColumnType("int")
                        .HasColumnName("cod_usuario_prestador");

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("int")
                        .HasColumnName("cupos_disponibles");

                    b.Property<int>("CuposTotales")
                        .HasColumnType("int")
                        .HasColumnName("cupos_totales");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Cod");

                    b.HasIndex("CodUsuarioPrestador");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Cupo", b =>
                {
                    b.Property<int>("CodCita")
                        .HasColumnType("int")
                        .HasColumnName("cod_cita");

                    b.Property<int>("CodUsuarioSolicitante")
                        .HasColumnType("int")
                        .HasColumnName("cod_usuario_solicitante");

                    b.Property<DateTime>("FechaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_reserva")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CodCita", "CodUsuarioSolicitante");

                    b.HasIndex("CodUsuarioSolicitante");

                    b.ToTable("cupos", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Prestador", b =>
                {
                    b.Property<int>("CodUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cod_usuario");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("especialidad");

                    b.HasKey("CodUsuario");

                    b.ToTable("prestadores", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cod"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Cod");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Solicitante", b =>
                {
                    b.Property<int>("CodUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cod_usuario");

                    b.HasKey("CodUsuario");

                    b.ToTable("solicitantes", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.SolicitantePrestador", b =>
                {
                    b.Property<int>("CodUsuarioSolicitante")
                        .HasColumnType("int")
                        .HasColumnName("cod_usuario_solicitante");

                    b.Property<int>("CodUsuarioPrestador")
                        .HasColumnType("int")
                        .HasColumnName("cod_usuario_prestador");

                    b.Property<DateTime>("FechaSuscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_suscripcion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CodUsuarioSolicitante", "CodUsuarioPrestador");

                    b.HasIndex("CodUsuarioPrestador");

                    b.ToTable("solicitantes_prestadores", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cod"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clave");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Cod");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("CodUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cod_usuario");

                    b.Property<int>("CodRol")
                        .HasColumnType("int")
                        .HasColumnName("cod_rol");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CodUsuario", "CodRol");

                    b.HasIndex("CodRol");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Cita", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Prestador", "Prestador")
                        .WithMany("Citas")
                        .HasForeignKey("CodUsuarioPrestador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Cupo", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Cita", "Cita")
                        .WithMany("Cupos")
                        .HasForeignKey("CodCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingSystem.Domain.Entities.Solicitante", "Solicitante")
                        .WithMany("Cupos")
                        .HasForeignKey("CodUsuarioSolicitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Prestador", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Prestador")
                        .HasForeignKey("BookingSystem.Domain.Entities.Prestador", "CodUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Solicitante", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Solicitante")
                        .HasForeignKey("BookingSystem.Domain.Entities.Solicitante", "CodUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.SolicitantePrestador", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Prestador", "Prestador")
                        .WithMany("Suscriptores")
                        .HasForeignKey("CodUsuarioPrestador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingSystem.Domain.Entities.Solicitante", "Solicitante")
                        .WithMany("Suscripciones")
                        .HasForeignKey("CodUsuarioSolicitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("CodRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingSystem.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("CodUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Cita", b =>
                {
                    b.Navigation("Cupos");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Prestador", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Suscriptores");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Solicitante", b =>
                {
                    b.Navigation("Cupos");

                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Prestador");

                    b.Navigation("Solicitante");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
